//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export class Roles
{
	public static DEVICE_USER: string = 'DeviceUser';
	public static APP_USER: string = 'AppUser';
}
export class JwtClaimNames
{
	public static ID: string = 'id';
	public static ROLE: string = 'rol';
	public static NAME: string = 'name';
}
